[package]
name = "svnui"
version = "0.4.22"
edition = "2024"
description = "A terminal UI client for SVN (Subversion), inspired by gitui"
repository = "https://github.com/LiuYinCarl/svnui"
keywords = ["svn", "subversion", "tui", "terminal"]
license = "MIT"

[dependencies]
crossbeam-channel = "0.5.16"
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
ratatui = { version = "0.30.2", features = ["underline-color"] }
tui-textarea-2 = "0.13.2"
unicode-width = "0.2"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "tree"
harness = false
