//! User-facing strings, centralized like gitui's `strings` module.

pub struct Title {
    pub status: &'static str,
    pub log: &'static str,
    pub log_detail: &'static str,
    pub patches: &'static str,
    pub help: &'static str,
    pub blame: &'static str,
    pub confirm: &'static str,
    pub message: &'static str,
    pub file_history: &'static str,
    pub file_finder: &'static str,
    pub log_search: &'static str,
}

pub const TITLE: Title = Title {
    status: "Files (svn status)",
    log: "Log (svn log)",
    log_detail: "Revision details",
    patches: "Patches",
    help: "Help",
    blame: "Blame",
    confirm: "Confirm",
    message: "Message",
    file_history: "File history",
    file_finder: "Find file",
    log_search: "Search commits",
};

pub struct Msg {
    pub loading: &'static str,
    pub no_working_copy: &'static str,
    pub empty_log: &'static str,
    pub empty_log_filtered: &'static str,
    pub empty_status: &'static str,
    pub commit_staged: &'static str,
    pub commit_nothing_staged: &'static str,
    pub revert_confirm: &'static str,
    pub update_confirm: &'static str,
    pub resolve_confirm: &'static str,
    pub update_to_rev_confirm: &'static str,
    pub add_done: &'static str,
    pub revert_done: &'static str,
    pub resolve_done: &'static str,
    pub empty_patches: &'static str,
    pub patch_saved: &'static str,
    pub patch_nothing_to_save: &'static str,
    pub patch_deleted: &'static str,
    pub apply_patch_confirm: &'static str,
    pub delete_patch_confirm: &'static str,
}

pub const MSG: Msg = Msg {
    loading: "Loading...",
    no_working_copy: "Error: not an SVN working copy (svn info failed)",
    empty_log: "No revisions found",
    empty_log_filtered: "No match in loaded commits — press / then Enter to search all history",
    empty_status: "Working copy is clean",
    commit_staged: "Commit staged changes?",
    commit_nothing_staged: "Nothing staged — stage files with space, or stage all with A",
    revert_confirm: "Revert local changes? (discards modifications)",
    update_confirm: "Run svn update?",
    resolve_confirm: "Resolve conflict using the working copy version?",
    update_to_rev_confirm: "Update working copy to selected revision?",
    add_done: "Added to version control",
    revert_done: "Reverted",
    resolve_done: "Conflict resolved",
    empty_patches: "No patches yet — press P to save the working-copy changes as a patch file",
    patch_saved: "Saved patch",
    patch_nothing_to_save: "No local changes — nothing to save as a patch",
    patch_deleted: "Deleted patch",
    apply_patch_confirm: "Apply this patch to the working copy? (svn patch)",
    delete_patch_confirm: "Delete this patch file?",
};
